### ISSUE TITLE
Error while reading a compose file

### ISSUE THREAD

**Issue by LucasSovre** [composecraft/composecraft#10]
An error while reading the following file happened :
```yaml
version: '3.7'
services:
#portainer
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    environment:
      - PUID:1000
      - PGID:1000
      - TZ=America/Edmonton
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/docker/config/portainer:/data
    ports:
      - 9000:9000
#ngninx
  nginx:
    container_name: nginx
    image: linuxserver/nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
    volumes:
      - ~/docker/config/nginx:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
#unifi controller
  unifi-network-application:
    image: linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
      - MONGO_USER=unifi
      - MONGO_PASS=Kzb9DZDpwT7Nr
      - MONGO_HOST=unifidb
      - MONGO_PORT=27017
      - MONGO_DBNAME=UNIFIDB
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
      - MONGO_TLS= #optional
      - MONGO_AUTHSOURCE= #optional
    volumes:
      - ~/docker/config/unificontroller:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
    depends_on:
      unifidb:
        condition: service_started
#unifi controller mongodb database
  unifidb:
    container_name: unifidb
    image: mongo:4.4
    environment:
      - TZ=America/Edmonton
    volumes:
      - ~/docker/config/unifidb:/data/db
      - ~/docker/config/unifidb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped
#vaultwarden
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server
    environment:
      - ENABLE_WEBSOCKET=true
      - PUSH_ENABLED=true
      - PUSH_INSTALLATION_ID=fa72c8ff-9d18-4b23-bab2-b12c01529a01
      - PUSH_INSTALLATION_KEY=LJDhkFVyRX9iHvZyOwn3
      - PUSH_RELAY_URI=https://push.bitwarden.com
      - PUSH_IDENTITY_URI=https://identity.bitwarden.com
      - ADMIN_TOKEN=jnrmBEKcaUbpHexHd4qpS6eeWV7EPbC5Kjg6g2Cw42c7pptFPvpfDUV7n8ux
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
    volumes:
      - ~/docker/config/vaultwarden:/data
    ports:
      - 9001:80
    restart: unless-stopped
#Gitlab
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ee:latest
    hostname: gitlab.tmlgroup.com
    environment:
     GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.tmlgroup.com'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        letsencrypt['enable'] = false
        gitlab_rails['gitlab_shell_ssh_port'] = 31022
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = 'mail.tmlgroup.com'                   
        gitlab_rails['smtp_port'] = '25'                                       
        gitlab_rails['smtp_domain'] = 'mail.tmlgroup.com'                    
        gitlab_rails['smtp_authentication'] = false                            
        gitlab_rails['gitlab_email_from'] = 'gitlab@tmlgroup.com'
        gitlab_rails['gitlab_email_reply_to'] = 'gitlab@tmlgroup.com'  
        gitlab_rails['omniauth_allow_single_sign_on'] = ['saml']
        gitlab_rails['omniauth_auto_link_saml_user'] = true
        gitlab_rails['omniauth_auto_sign_in_with_provider'] = 'saml'
        gitlab_rails['omniauth_providers'] = [
          {
            name: "saml",
            label: "Microsoft Azure",
            args: {
              assertion_consumer_service_url: "https://gitlab.tmlgroup.com/users/auth/saml/callback",
              idp_cert: "-----BEGIN CERTIFICATE-----MIIC8DCCAdigAwIBAgIQNgWQjdUU9pRMSvvyJjwGsDANBgkqhkiG9w0BAQsFADA0MTIwMAYDVQQDEylNaWNyb3NvZnQgQXp1cmUgRmVkZXJhdGVkIFNTTyBDZXJ0aWZpY2F0ZTAeFw0yMzAyMTUxODI3NDJaFw0yNjAyMTUxODI3NDFaMDQxMjAwBgNVBAMTKU1pY3Jvc29mdCBBenVyZSBGZWRlcmF0ZWQgU1NPIENlcnRpZmljYXRlMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtnmpA2V+hyE6XmTwBWpwcJlX9FzWz/rMP9017tf+ZIe03+tPfUbvxOZFeXD2D6Jrkf8q5grQ3VZD5WLESn5TdZSenXhkZoxh54I3C4fn1oY/KZuGyP+nwRb6p08OnDAo7zTMxwS3zBG+J8LTmGwpHSRyAcPXrqmRnOX4CvbNbUnDz9GGCX8O58pS7Hu3RL3OjeTKetsC9wEvdkZCpisnkwshfJvBYP5FKvyR/+6k2tqsFIrZ5CsLfXBIXCbf/ojSEaWTpFRiVUf9Xkr2RADX0bvsCSuBQAwGdqtawT5+hBD5PdmuCQEwq8hVvIZgHqluZMeCQy3/9etzHtdORa0qsQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBLo6SekrNKjH8WK8eiaU9NDyThfj33/Isj6meVqcXZJ8Q4zyt/rN9ZsrzgT82G+IhziRJcnVXpkjPrtTitSmpU2kXWl/wDVbQ1ZOB5ODkqjrah8QvR07bTUz/r//bVTAUcFSZ79u6jB9USH4AsctejAU0o/Pb/bf5Wght0gR5DH9QZH3hbQR5IGhhpDPMP7HhHwxMAbKrrIzvexpqEiSyOodYHu/FyPPUNVNfkROt5BPS3CV0To4twnWFTRkptWD0n1GBCd25mnvMp0axi6RHlkY5SMm2EcOPZKqAGIVA4eNIZBpcQye5XoF6zE8P8VUJNOexvjduXHXeiDHc6VEya-----END CERTIFICATE-----",
              idp_sso_target_url: "https://login.microsoftonline.com/467e4cb3-02c4-4b53-b6e3-438846ae3950/saml2",
              issuer: "https://gitlab.tmlgroup.com",
              name_identifier_format: "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent",
              attribute_statements: { email: ['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress'] }
            }
          }
        ]

    volumes:
      - ~/docker/config/gitlab/config:/etc/gitlab
      - ~/docker/config/gitlab/logs:/var/log/gitlab
      - ~/docker/config/gitlab/data:/var/opt/gitlab
    ports:
     - 9002:80
     - 31022:22
    shm_size: 256m
    restart: unless-stopped
#Gophish
  gophish:
    container_name: gophish
    image: gophish/gophish
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
    volumes:
      - type: bind
        source: ~/docker/config/gophish/gophish.db
        target: /opt/gophish/gophish.db
        source: ~/docker/config/gophish/config.json
        target: /opt/gophish/config.json
    ports:
      - 3333:3333
      - 8777:8777
    restart: unless-stopped
    depends_on:
      gophishdb:
        condition: service_started
#Gophish MySQL
  gophishdb:
    container_name: gophishdb
    image: mysql:8.0
    command: --sql_mode=IGNORE_SPACE,ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    environment:
      MYSQL_DATABASE: 'gophishdb'
      MYSQL_USER: 'gophishadmin'
      MYSQL_PASSWORD: 'gophish'
      MYSQL_ROOT_PASSWORD: 'gophishroot'
    ports:
      - 3306:3306
    expose:
      - '3306'
    volumes:
      - type: bind
        source: ~/docker/config/mysql
        target: /var/lib/mysql
        #source: ~/docker/config/mysql/my.cnf
        #target: /etc/my.cnf
volumes:
  gophishdb:

```
    
To solve this issue, a test including this file have to be added.
