### ISSUE TITLE
Redirect-policy resets to none

### ISSUE THREAD

**Issue by WolfwithSword** [composecraft/composecraft#17]
After importing a compose file, or creating one from scratch, if I set the `restart-policy` on the service, it will save and be displayed in the code view, but as soon as anything loads or refreshes it, it is lost. Additionally on importing of a compose file with restart-policies set, it *removes* all cases of restart policy.

Example import
```
name: CustomAPI
services:
  my-api:
    image: my-local-docker-image:latest
    ports:
      - 14111:14111
    entrypoint:
      - /home/user/Desktop/workspace/entrypoint.sh
    restart: unless-stopped
    volumes:
      - /home/user/Desktop/workspace:/home/user/Desktop/workspace
      - /dev/bus/usb:/dev/bus/usb
```

![image](https://github.com/user-attachments/assets/df59e35d-3d43-4db5-864d-3f11c26e69b4)
