### ISSUE TITLE
Share URL does not render diagram

### ISSUE THREAD

**Issue by WolfwithSword** [composecraft/composecraft#18]
This one may be partly due to my environment setup, but would love to troubleshoot it and figure it out.

Currently, when I make a compose file / diagram, I click the share button to generate a link. When I access this link, I do not see anything rendered in the canvas.

![image](https://github.com/user-attachments/assets/3e7ba1e9-4fc8-4796-b2e9-5e75fef33680)

My Environment:
**Self-hosted** Yes, docker via Unraid
**Browser** Edge & Opera GX, on Windows 11

I also run this through a reverse proxy (Domain/DNS through Cloudflare, reverse proxy managed via Traefik). I have allowed certain CORS headers to remove that worry. Additionally, I use Authentik as a middleware auth as I would like to limit access to this instance (ideally, I could integrate this auth via LDAP or SSO or SAML or w/e and replace the authentication withing ComposeCraft). 

Checking the console logging, I do see a redirect to `/?_rsc`  that returns a 302 error when behind my auth, despite allowing that url and `/share` to be unauth'ed.  

However, I have also tried disabling my auth middleware entirely, and even trying to access the `/share` URL via the local self-hosted IP of my ComposeCraft instance, without any proxy or auth in between, and it still does not render.

**Comment by LucasSovre** [comment]
could you share your environment file (without any sensitive data) ? have you set the correct URL ENV ?

**Comment by WolfwithSword** [comment]
> could you share your environment file (without any sensitive data) ? have you set the correct URL ENV ?

I've set the `URL` env var to `https://subdomain.domain.com`,  replacing subdomain and domain respectively.

Currently the only other env vars I have are `MONBODB_URI`, `CORE_ONLY`=true, `DISABLE_TELEMETRY`=true, `GITHUB_CLIENT_ID`, `GITHUB_CLIENT_SECRET`, and `SECRET_KEY`

**Comment by drilus** [comment]
I'm also having this issue.

Here's the compose file I'm using that produces this exact result:
$HOSTNAME=subdomain.domain.com

```yaml
name: compose_craft
services:
  composecraft:
    image: composecraft/composecraft:latest
    ports:
      - 3123:3000
    environment:
      - CORE_ONLY=true
      - URL=https://${HOSTNAME}
      - SECRET_KEY=${SECRET_KEY}
      - MONGODB_URI=mongodb://${DB_USERNAME}:${DB_PASSWORD}@db
    labels:
      - net.unraid.docker.webui=https://${HOSTNAME}
      - net.unraid.docker.icon=https://raw.githubusercontent.com/composecraft/composecraft/743a31be967c8ee9e61ad520ef50df604babcc05/assets/logo.png
    depends_on:
      - db
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - /mnt/user/appdata/composecraft/db:/data/db
```
