### ISSUE TITLE
Port parsing only supports simple port declarations

### ISSUE THREAD

**Issue by Ranbato** [composecraft/composecraft#20]
I've got some services that declare port ranges and/or include TCP or UDP in the declaration.
These silently get converted to NaN when importing.

I'd recommend 3 changes:
1. Error or warn whenever import parsing fails
2. Fields that aren't successfully parsed should be stored as strings so their contents aren't lost.  Multiple advantages to implementing this.  The first is that it allows users to work around missing/buggy functionality but still use the tool and so reduce the number of users who bounce off when they try the tool and encounter an issue. This can also be used to provide the _advanced_ ability to edit them freeform even when unrecognized.  
3. Enhance the port parsing to support the rest of the spec.

Here are some examples
```
 nextpvr
    image: nextpvr/nextpvr_amd64:stable
    ports:
      - 8866:8866
      - 8020-8030:8020-8030/udp
      - 16891:16891/udp
    devices:
      - /dev/dri:/dev/dri
    restart: always
 controller:
    image: jacobalberty/unifi:v8.0.26
    container_name: unifi_controller
    depends_on:
      - mongo
    init: true
    networks:
      - shared
    restart: always
    volumes:
      - unifidir:/unifi
      - unifiinit:/unifi/init.d
      - unifirun:/var/run/unifi
      #      - unifidata:/unifi/data
      # Mount local folder for backups and autobackups
      - /volume1/config/unifi/backup:/unifi/data/backup
      - /volume1/config/unifi/cert:/unifi/cert
      - /volume1/config/unifi/log:/unifi/log
      - /volume1/config/unifi/data:/unifi/data
    user: unifi
    mem_limit: "1024M"
    #    sysctls:
    #      net.ipv4.ip_unprivileged_port_start: 0
    env_file:
      - ./.env
    environment:
      - DB_URI=mongodb://mongo/unifi
      - STATDB_URI=mongodb://mongo/unifi_stat
      - DB_NAME=<redacted>
      - UNIFI_UID=1028
      - UNIFI_GID=100
      - RUNAS_UID0=false
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8444:8443/tcp" # Controller GUI/API as seen in a web browser
      #      - "8880:8880/tcp" # HTTP portal redirection
      #      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
```
