### ISSUE TITLE
Error while reading a compose file

### ISSUE THREAD

**Issue by LucasSovre** [composecraft/composecraft#21]
An error while reading the following file happened :
```yaml
=====================================================================================================================


arc
"/srv/dev-disk-by-uuid-80d6513d-2047-4609-a6a7-197e265d2e09/ussd/"

"/srv/dev-disk-by-uuid-cd0f234d-9959-4819-84c4-f8ad92973668/nvme1/aria2p/arc_4GB-24.1.14f.img/arc_4GB.img"

"/srv/dev-disk-by-uuid-cd0f234d-9959-4819-84c4-f8ad92973668/nvme1/aria2p/arc-24.1.14f.img/arc.img"


mkdir -m 777 -p /srv/dev-disk-by-uuid-80d6513d-2047-4609-a6a7-197e265d2e09/ussd/arc/

cd /srv/dev-disk-by-uuid-80d6513d-2047-4609-a6a7-197e265d2e09/ussd/arc/



cp -r "/srv/dev-disk-by-uuid-cd0f234d-9959-4819-84c4-f8ad92973668/nvme1/aria2p/arc_4GB-24.1.14f.img/arc_4GB.img" "/srv/dev-disk-by-uuid-80d6513d-2047-4609-a6a7-197e265d2e09/ussd/arc/custom.iso"
cp -r "/srv/dev-disk-by-uuid-cd0f234d-9959-4819-84c4-f8ad92973668/nvme1/aria2p/arc_4GB-24.1.14f.img/arc_4GB.img" "/srv/dev-disk-by-uuid-80d6513d-2047-4609-a6a7-197e265d2e09/ussd/arc/custom.img"



cp -r "/srv/dev-disk-by-uuid-cd0f234d-9959-4819-84c4-f8ad92973668/nvme1/aria2p/arc-24.1.14f.img/arc.iso" "/srv/dev-disk-by-uuid-80d6513d-2047-4609-a6a7-197e265d2e09/ussd/arc/custom.iso"



cp -r "/srv/dev-disk-by-uuid-cd0f234d-9959-4819-84c4-f8ad92973668/nvme1/aria2p/arc-24.1.14f.img/arc.img" "/srv/dev-disk-by-uuid-80d6513d-2047-4609-a6a7-197e265d2e09/ussd/arc/custom.iso"
cp -r "/srv/dev-disk-by-uuid-cd0f234d-9959-4819-84c4-f8ad92973668/nvme1/aria2p/arc-24.1.14f.img/arc.img" "/srv/dev-disk-by-uuid-80d6513d-2047-4609-a6a7-197e265d2e09/ussd/arc/boot.img"
cp -r "/srv/dev-disk-by-uuid-cd0f234d-9959-4819-84c4-f8ad92973668/nvme1/aria2p/arc-24.1.14f.img/arc.img" "/srv/dev-disk-by-uuid-80d6513d-2047-4609-a6a7-197e265d2e09/ussd/arc.img"



chmod +x "/srv/dev-disk-by-uuid-80d6513d-2047-4609-a6a7-197e265d2e09/ussd/arc/custom.iso"
chmod +x "/srv/dev-disk-by-uuid-80d6513d-2047-4609-a6a7-197e265d2e09/ussd/arc/custom.img"
chmod +x "/srv/dev-disk-by-uuid-80d6513d-2047-4609-a6a7-197e265d2e09/ussd/arc/boot.img"

chmod 777 -R "/srv/dev-disk-by-uuid-80d6513d-2047-4609-a6a7-197e265d2e09/ussd/arc/"





"/srv/dev-disk-by-uuid-80d6513d-2047-4609-a6a7-197e265d2e09/ussd/arc/"



chmod 777 -R "/srv/dev-disk-by-uuid-80d6513d-2047-4609-a6a7-197e265d2e09/ussd/arc/"



chmod +x "/srv/dev-disk-by-uuid-80d6513d-2047-4609-a6a7-197e265d2e09/ussd/arc/data.qcow2"
chmod +x "/srv/dev-disk-by-uuid-80d6513d-2047-4609-a6a7-197e265d2e09/ussd/arc/boot.img"

=====================================================================================================================


---
version: "3.7"
services:
  arc:
    image: qemux/qemu-docker:latest
    container_name: arc
    hostname: arc
    #network_mode: bridge
    networks:
      192.168.1.xxx:
        ipv4_address: 192.168.1.32
    stop_grace_period: 2m
    privileged: true
    user: root
    cap_add:
      -  NET_ADMIN
    environment:
      - PUID=1000
      - PGID=100
      - GIDLIST=6,44,106,99,1000
      - UMASK_SET=000
      - TZ=America/New_York
      - DISK_PATH=/storage
      #- BOOT=https://github.com/AuxXxilium/arc/releases/download/24.1.14f/arc-24.1.14f.img.zip
      - BOOT=boot.img
      #- BOOT_MODE=uefi
      - BOOT_MODE=bio
      #- DISPLAY=vnc
      - DISPLAY=web
      - CPU_CORES=2
      - RAM_SIZE=4G
      - DISK_SIZE=100G
      - ATTENDED=Y
      - GPU=Y
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /srv/dev-disk-by-uuid-80d6513d-2047-4609-a6a7-197e265d2e09/ussd/arc/boot.img:/storage/boot.img
      - /srv/dev-disk-by-uuid-80d6513d-2047-4609-a6a7-197e265d2e09/ussd/arc/:/storage
      - /srv/dev-disk-by-uuid-80d6513d-2047-4609-a6a7-197e265d2e09/ussd/arc/:/bootloader
    devices:
      - /dev/dri:/dev/dri
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/card1:/dev/dri/card1
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/renderD129:/dev/dri/renderD129
      - /dev/kfd:/dev/kfd
      - /dev/fb0:/dev/fb0
      - /dev/lirc0:/dev/lirc0
      - /dev/vbi0:/dev/vbi0
      - /dev/kvm:/dev/kvm
      - /dev/vhost-net:/dev/vhost-net
      - /dev/media0:/dev/media0
    ports:
      - 8006:8006
      - 5900:5900
      - 22:22
    device_cgroup_rules:
      - 'c *:* rwm'
    dns:
      - 192.168.1.1
    logging:
      driver: json-file
      options: {}
    restart: unless-stopped

networks:
    192.168.1.xxx:
      external: true





=====================================================================================================================

---
version: "3.7"
services:
  arc:
    image: dockurr/windows:latest
    container_name: arc
    hostname: arc
    #network_mode: bridge
    networks:
      192.168.1.xxx:
        ipv4_address: 192.168.1.32
    stop_grace_period: 2m
    privileged: true
    user: root
    runtime: nvidia
    cap_add:
      -  NET_ADMIN
    environment:
      - PUID=1000
      - PGID=100
      - GIDLIST=6,44,106,99,1000
      - UMASK_SET=000
      - TZ=America/New_York
      - VERSION=win10x64
      - CPU_CORES=2
      - RAM_SIZE=4G
      - DISK_SIZE=100G
      - ATTENDED=Y
      - GPU=Y
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /srv/dev-disk-by-uuid-468fbdbb-a0cb-4a65-8c1b-4782fc1441e7/nvme/database/windows10/:/storage
    devices:
      - /dev/dri:/dev/dri
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/card1:/dev/dri/card1
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/renderD129:/dev/dri/renderD129
      - /dev/kfd:/dev/kfd
      - /dev/fb0:/dev/fb0
      - /dev/lirc0:/dev/lirc0
      - /dev/vbi0:/dev/vbi0
      - /dev/kvm:/dev/kvm
      - /dev/vhost-net:/dev/vhost-net
      - /dev/media0:/dev/media0
      - /dev/nvidia-caps/:/dev/nvidia-caps/
      - /dev/nvidia-caps/nvidia-cap1:/dev/nvidia-caps/nvidia-cap1
      - /dev/nvidia-caps/nvidia-cap2:/dev/nvidia-caps/nvidia-cap2
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
    ports:
      - 8006:8006
    device_cgroup_rules:
      - 'c *:* rwm'
    dns:
      - 192.168.1.1
    logging:
      driver: json-file
      options: {}
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


networks:
    192.168.1.xxx:
      external: true
```
    
To solve this issue, a test including this file have to be added.
