### ISSUE TITLE
Error while reading a compose file

### ISSUE THREAD

**Issue by LucasSovre** [composecraft/composecraft#24]
An error while reading the following file happened :
```yaml
services:
  bunkerweb:
    image: bunkerity/bunkerweb:1.5.12
    ports:
      - "80:8080"
      - "443:8443"
    labels:
      bunkerweb.INSTANCE: "yes"
    environment:
      SERVER_NAME: "dvx.me"
      DATABASE_URI: "mariadb+pymysql://bunkerweb:zXwwS98rNFHRx9eE6dxy@bw-db:3306/db"
      AUTOCONF_MODE: "yes"
      MULTISITEL: "yes"
      API_WHITELIST_IP: "127.0.0.0/8 10.20.30.0/24"
      UI_HOST: "http://bw-ui:7000" # Change it if needed
      LETS_ENCRYPT_CLEAR_OLD_CERTS: "yes"
      EXTERNAL_PLUGIN_URLS: "https://github.com/bunkerity/bunkerweb-plugins/archive/refs/tags/v1.6.zip"
    networks:
      - bw-universe
      - bw-services

  bw-autoconf:
    image: bunkerity/bunkerweb-autoconf:1.5.12
    depends_on:
      - bunkerweb
      - bw-docker
    environment:
      DATABASE_URI: "mariadb+pymysql://bunkerweb:zXwwS98rNFHRx9eE6dxy@bw-db:3306/db"
      AUTOCONF_MODE: "yes"
      DOCKER_HOST: "tcp://bw-docker:2375"
    networks:
      - bw-universe
      - bw-docker

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.5.12
    depends_on:
      - bunkerweb
      - bw-docker
    environment:
      DATABASE_URI: "mariadb+pymysql://bunkerweb:zXwwS98rNFHRx9eE6dxy@bw-db:3306/db"
      DOCKER_HOST: "tcp://bw-docker:2375"
      AUTOCONF_MODE: "yes"
    networks:
      - bw-universe
      - bw-docker

  bw-docker:
    image: tecnativa/docker-socket-proxy:nightly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: "1"
      LOG_LEVEL: "warning"
    networks:
      - bw-docker

  bw-db:
    image: mariadb:10.10
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "bunkerweb"
      MYSQL_PASSWORD: "zXwwS98rNFHRx9eE6dxy"
    volumes:
      - /storage/docker-app/bunkerweb/db:/var/lib/mysql
    networks:
      - bw-docker

  bw-ui:
    image: bunkerity/bunkerweb-ui:1.5.12
    networks:
      bw-docker:
      bw-universe:
        aliases:
          - bw-ui
    environment:
      AUTOCONF_MODE: "yes"
      DOCKER_HOST: "tcp://bw-docker:2375"
      DATABASE_URI: "mariadb+pymysql://bunkerweb:zXwwS98rNFHRx9eE6dxy@bw-db:3306/db" # Remember to set a stronger password for the database
      bunkerweb.SERVER_NAME: bunkerweb.dvx.me
      bunkerweb.USE_REVERSE_PROXY: yes
      bunkerweb.REVERSE_PROXY_URL: /
      bunkerweb.REVERSE_PROXY_HOST: http://bw-ui:7000
      bunkerweb.REVERSE_PROXY_INTERCEPT_ERRORSL: no
      bunkerweb.BLACKLIST_COUNTRY: KP IR RU CN SY CU VE SD BY
      bunkerweb.AUTO_LETS_ENCRYPT: yes
      bunkerweb.EMAIL_LETS_ENCRYPT: admin@dvx.me
      bunkerweb.REDIRECT_HTTP_TO_HTTPS: yes
      bunkerweb.INTERCEPTED_ERROR_CODES: 400 404 405 413 429 500 501 502 503 504

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-docker:
    name: bw-docker
```
    
To solve this issue, a test including this file have to be added.
