### ISSUE TITLE
Error while reading a compose file

### ISSUE THREAD

**Issue by LucasSovre** [composecraft/composecraft#26]
An error while reading the following file happened :
```yaml
default:
  email_delivery:
    delivery_method: :smtp
  smtp_settings:
    address: smtp.bizmail.yahoo.com
    port: 465
    ssl: true
    enable_starttls_auto: true
    domain: amicigroup.net
    authentication: :login
    user_name: qc.redmine@amicigroup.net
    password: tblntzeehcogifiz
```
    
To solve this issue, a test including this file have to be added.
