### ISSUE TITLE
Import Strips Secrets from compose

### ISSUE THREAD

**Issue by theoisadoor** [composecraft/composecraft#37]
### Is the instance self-hosted or cloud?

Self-hosted

### Which browser do you use?

Firefox,Safari

### What OS do you use?

Ubuntu 22.04,macOS 15.3

### Describe the bug

When importing an existing `docker-compose.yml` file with `secrets`, they are stripped from the output code, and likewise not displayed on the "map".
Presumably this is because compute-craft does not yet have the support for secrets, please correct me if I am wrong.

eg. sample input file:
```
services:
   influxdb2:
    image: influxdb:2
    container_name: influxdb2
    restart: always
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: docs
      DOCKER_INFLUXDB_INIT_BUCKET: home
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2

  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: unless-stopped
    depends_on:
      - influxdb2
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb2
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana

secrets:
  influxdb2-admin-username:
    file: ./secrets/.env.influxdb2-admin-username
  influxdb2-admin-password:
    file: ./secrets/.env.influxdb2-admin-password
  influxdb2-admin-token:
    file: ./secrets/.env.influxdb2-admin-token

volumes:
  influxdb2-data:
  influxdb2-config:
  grafana-data:
```

Code after importing into compose-craft:
```
name: artemis_kid
services:
  influxdb2:
    image: influxdb:2
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME_FILE=/run/secrets/influxdb2-admin-username
      - DOCKER_INFLUXDB_INIT_PASSWORD_FILE=/run/secrets/influxdb2-admin-password
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE=/run/secrets/influxdb2-admin-token
      - DOCKER_INFLUXDB_INIT_ORG=docs
      - DOCKER_INFLUXDB_INIT_BUCKET=home
    networks:
      - eris_joey
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=""
    depends_on:
      - influxdb2
    networks:
      - eris_joey
    volumes:
      - grafana-data:/var/lib/grafana
networks:
  eris_joey:
    driver: bridge
    attachable: false
    external: false
volumes:
  influxdb2-data:
    driver: local
    external: false
  influxdb2-config:
    driver: local
    external: false
  grafana-data:
    driver: local
    external: false
```

### Environment variables (non-sensitive)

environment:
      - CORE_ONLY=true
      - URL=http://localhost:3000
      - SECRET_KEY=changeme
      - MONGODB_URI=mongodb://dev:dev@db
