### ISSUE TITLE
services: command & healthcheck string

### ISSUE THREAD

**Issue by Vladimir-Va** [composecraft/composecraft#39]
Hello Compose Craft team.
If I need to make such a construction:
```
command:
      - /bin/sh
      - -c
      - redis-server --requirepass redispass
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
```
But CC generates this code, and I haven't found a way to format the string in the form I need:
```
    command:
      - /bin/sh
      - -c
      - "`redis-server"
      - --requirepass
      - redispass`
    healthcheck:
      test:
        - CMD
        - '["CMD-SHELL",'
        - '"redis-cli'
        - ping
        - "||"
        - exit
        - 1"]
```

How can these sections be formatted and maybe it makes sense to add commands line by line (like as Bindings volumes)?
