### ISSUE TITLE
Error while reading a compose file

### ISSUE THREAD

**Issue by LucasSovre** [composecraft/composecraft#5]
An error while reading the following file happened :
```yaml
#ConfigMap configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <html>
      <head><title>Mon site Nginx</title></head>
      <body><h1>Bienvenue sur mon site !</h1></body>
    </html>

---
# Deployment configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx # Label for the deployment
  name: nginx-deployment # Name of the deployment
spec:
  replicas: 3 # Number of pod replicas
  selector:
    matchLabels:
      app: nginx # Selector to match pods with this label
  template: # Pod template
    metadata:
      labels:
        app: nginx # Label for the pods
    spec:
      containers:
        - name: nginx-container # Name of the container
          image: nginx:1.27.3 # Docker image to use
          imagePullPolicy: IfNotPresent # Image pull policy
          resources:
            limits:
              cpu: 2 # Maximum CPU units
              memory: 200Mi # Maximum memory
            requests:
              cpu: 100m # Minimum CPU units
              memory: 10Mi # Minimum memory
          ports:
            - containerPort: 80 # Port exposed by the container
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html # Emplacement par défaut pour les fichiers HTML de Nginx
          livenessProbe:
            httpGet:
              path: / # Health check endpoint for liveness
              port: 80
            initialDelaySeconds: 3 # Start checking after 3 seconds
            periodSeconds: 5 # Check every 5 seconds
            failureThreshold: 3 # After 3 failures, restart the container
            successThreshold: 1 # 1 success needed to consider it healthy
      volumes:
        - name: html-volume
          configMap:
            name: nginx-html # Référence au ConfigMap contenant les fichiers HTML

---
# Service configuration
apiVersion: v1
kind: Service
metadata:
  name: nginx-service # Name of the service
spec:
  ports:
    - port: 80 # Port exposed by the service
      protocol: TCP # Protocol used by the service
      targetPort: 80 # Target port on the container
  selector:
    app: nginx # Selector to match pods with this label
  type: LoadBalancer # Type of service (LoadBalancer)

```
    
To solve this issue, a test including this file have to be added.
