### ISSUE TITLE
Error while reading a compose file

### ISSUE THREAD

**Issue by LucasSovre** [composecraft/composecraft#9]
An error while reading the following file happened :
```yaml
services:
  frigate:
    deploy:    # Nvidia GPU support
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "64mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
              
  ha:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: ha
    network_mode: npm
    privileged: true
    volumes:
      - ./ha:/config
    ports:
      - 8123:8123
    restart: unless-stopped
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    network_mode: ha
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    
```
    
To solve this issue, a test including this file have to be added.
